// <auto-generated />
namespace DawV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OkNotice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OkNotice));
        
        string IMigrationMetadata.Id
        {
            get { return "202101041903135_OkNotice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
